<header class="flex flex-wrap items-center justify-between gap-6 px-6 py-6 sm:px-10 lg:px-16">
    <a class="sr-only focus:not-sr-only focus:absolute focus:z-50 focus:rounded focus:bg-[var(--color-text)] focus:px-4 focus:py-3 focus:text-sm focus:font-semibold focus:text-[var(--color-text-dark)] focus:ring-4 focus:ring-[var(--color-medium-purple-500)]" href="#contenu">Aller au contenu principal</a>

    <a class="flex items-center gap-2 font-['Tanker'] text-2xl tracking-normal" href="{{ route('home.index') }}">
        <span class="flex h-8 w-8 items-center justify-center rounded-full bg-[var(--color-purple-500)] text-xl text-[var(--color-text)]" aria-hidden="true">+</span>
        <span>TOP<span class="text-[var(--color-medium-purple-400)]">DIFF</span></span>
    </a>

    <div class="order-3 flex w-full flex-col gap-4 sm:order-2 sm:w-auto sm:flex-1 sm:items-center sm:justify-center">
        <nav class="flex flex-wrap items-start justify-center gap-5 text-xs font-semibold uppercase tracking-widest">
            <details class="group relative">
                <summary class="{{ request()->routeIs('home.index') ? 'border-[var(--color-medium-purple-500)] text-[var(--color-medium-purple-400)]' : 'border-transparent hover:border-[var(--color-medium-purple-500)] hover:text-[var(--color-medium-purple-400)]' }} cursor-pointer list-none border-b-2 pb-1 transition focus:bg-[var(--color-medium-purple-950)] focus:px-2 focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-[var(--color-medium-purple-500)] focus:ring-offset-2">Accueil <span aria-hidden="true" class="ml-1 inline-block transition group-open:rotate-180">↓</span></summary>
                <div class="absolute left-1/2 z-20 mt-2 w-52 -translate-x-1/2 rounded-2xl border border-[var(--color-border)] bg-[var(--color-background)] p-2 shadow-[0_20px_60px_rgba(0,0,0,0.2)]">
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('home.index') }}#contenu">Contenu</a>
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('home.index') }}#disciplines">Disciplines</a>
                </div>
            </details>

            <details class="group relative">
                <summary class="{{ request()->routeIs('calisthenics.index') ? 'border-[var(--color-medium-purple-500)] text-[var(--color-medium-purple-400)]' : 'border-transparent hover:border-[var(--color-medium-purple-500)] hover:text-[var(--color-medium-purple-400)]' }} cursor-pointer list-none border-b-2 pb-1 transition focus:bg-[var(--color-medium-purple-950)] focus:px-2 focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-[var(--color-medium-purple-500)] focus:ring-offset-2">Callisthénie <span aria-hidden="true" class="ml-1 inline-block transition group-open:rotate-180">↓</span></summary>
                <div class="absolute left-1/2 z-20 mt-2 w-52 -translate-x-1/2 rounded-2xl border border-[var(--color-border)] bg-[var(--color-background)] p-2 shadow-[0_20px_60px_rgba(0,0,0,0.2)]">
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('calisthenics.index') }}#contenu">Contenu</a>
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('calisthenics.index') }}#benefices">Bénéfices</a>
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('calisthenics.index') }}#photos">Photos</a>
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('calisthenics.index') }}#faq">FAQ</a>
                </div>
            </details>

            <details class="group relative">
                <summary class="{{ request()->routeIs('musculation.index') ? 'border-[var(--color-medium-purple-500)] text-[var(--color-medium-purple-400)]' : 'border-transparent hover:border-[var(--color-medium-purple-500)] hover:text-[var(--color-medium-purple-400)]' }} cursor-pointer list-none border-b-2 pb-1 transition focus:bg-[var(--color-medium-purple-950)] focus:px-2 focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-[var(--color-medium-purple-500)] focus:ring-offset-2">Musculation <span aria-hidden="true" class="ml-1 inline-block transition group-open:rotate-180">↓</span></summary>
                <div class="absolute left-1/2 z-20 mt-2 w-52 -translate-x-1/2 rounded-2xl border border-[var(--color-border)] bg-[var(--color-background)] p-2 shadow-[0_20px_60px_rgba(0,0,0,0.2)]">
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('musculation.index') }}#contenu-principal">Contenu</a>
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('musculation.index') }}#presentation">Présentation</a>
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('musculation.index') }}#organisation">Organisation</a>
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('musculation.index') }}#exercices">Exercices</a>
                </div>
            </details>

            <details class="group relative">
                <summary class="{{ request()->routeIs('diet.index') ? 'border-[var(--color-medium-purple-500)] text-[var(--color-medium-purple-400)]' : 'border-transparent hover:border-[var(--color-medium-purple-500)] hover:text-[var(--color-medium-purple-400)]' }} cursor-pointer list-none border-b-2 pb-1 transition focus:bg-[var(--color-medium-purple-950)] focus:px-2 focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-[var(--color-medium-purple-500)] focus:ring-offset-2">Nutrition <span aria-hidden="true" class="ml-1 inline-block transition group-open:rotate-180">↓</span></summary>
                <div class="absolute right-0 z-20 mt-2 w-52 rounded-2xl border border-[var(--color-border)] bg-[var(--color-background)] p-2 shadow-[0_20px_60px_rgba(0,0,0,0.2)]">
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('diet.index') }}#contenu">Contenu</a>
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('diet.index') }}#bases">Les bases</a>
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('diet.index') }}#proteines">Protéines</a>
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('diet.index') }}#rythme">Rythme</a>
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('diet.index') }}#hydratation">Hydratation</a>
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('diet.index') }}#objectifs">Objectifs</a>
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('diet.index') }}#apports">Apports</a>
                    <a class="block rounded-xl px-3 py-2 text-left text-xs normal-case tracking-normal transition hover:bg-[var(--color-medium-purple-950)] focus:bg-[var(--color-medium-purple-950)] focus:text-[var(--color-text)] focus:outline-none focus:ring-4 focus:ring-inset focus:ring-[var(--color-medium-purple-500)]" href="{{ route('diet.index') }}#adapter">Adapter</a>
                </div>
            </details>
        </nav>
    </div>

    <form class="order-2 flex w-full items-center gap-2 sm:order-3 sm:w-auto" action="{{ route('sitemap.index') }}" method="get">
        <label class="sr-only" for="site-search">Rechercher sur le site</label>
        <input id="site-search" name="q" type="search" value="{{ request('q') }}" class="w-full min-w-0 rounded-full border border-[var(--color-border)] bg-transparent px-4 py-2 text-sm text-[var(--color-text)] placeholder:text-[var(--color-text-muted)] focus:outline-none focus:ring-4 focus:ring-[var(--color-medium-purple-500)] sm:w-56" placeholder="Rechercher">
        <button type="submit" class="inline-flex items-center gap-2 rounded-full bg-[var(--color-text)] px-4 py-2 text-xs font-semibold uppercase tracking-widest text-[var(--color-text-dark)] transition hover:bg-[var(--color-medium-purple-500)] hover:text-[var(--color-text-dark)]">
            Rechercher
        </button>
    </form>
</header>
